server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: user
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: update
  liquibase:
    enabled: true
    drop-first: true
    change-log: db.crypto-currency.xml
    url: jdbc:h2:mem:mydb
    user: user
    password: user

coins:
  ids:
    - 90
    - 80
    - 48543

update-interval: PT01M

volatility: 0.01
